const bdInitialAssignment=[{"id":208,"nom":"Gregory Galli","nomEleve":"Blinny","matiere":"Grails","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-10-07","note":9},
{"id":265,"nom":"Alisson Temin","nomEleve":"Sharron","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-04-19","note":2},
{"id":271,"nom":"Gabriel Mopolo","nomEleve":"Danna","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-11-13","note":14},
{"id":227,"nom":"Alisson Temin","nomEleve":"Kevin","matiere":"Analyse","imageMat":"assets/images/r.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-10-10","note":8},
{"id":216,"nom":"Serge Miranda","nomEleve":"Liesa","matiere":"De Base de données à Big Data","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-09-17","note":3},
{"id":260,"nom":"Buffa Michel","nomEleve":"Tracey","matiere":"Techno Web","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-12-02","note":15},
{"id":219,"nom":"Serge Miranda","nomEleve":"Andriana","matiere":"De Base de données à Big Data","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-07-24","note":7},
{"id":206,"nom":"Gabriel Mopolo","nomEleve":"Dion","matiere":"oracle","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2021-01-08","note":20},
{"id":202,"nom":"Buffa Michel","nomEleve":"Alric","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-01-07","note":3},
{"id":298,"nom":"Gabriel Mopolo","nomEleve":"Iorgo","matiere":"oracle","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-11-11","note":6},
{"id":243,"nom":"Serge Miranda","nomEleve":"Moore","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-04-20","note":13},
{"id":210,"nom":"Alisson Temin","nomEleve":"Dena","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-05-24","note":17},
{"id":258,"nom":"Gabriel Mopolo","nomEleve":"Ragnar","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-12-07","note":12},
{"id":238,"nom":"Buffa Michel","nomEleve":"Pearl","matiere":"Techno Web","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-02-24","note":7},
{"id":236,"nom":"Gabriel Mopolo","nomEleve":"Travus","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-06-21","note":15},
{"id":278,"nom":"Gabriel Mopolo","nomEleve":"Basia","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-11-16","note":7},
{"id":268,"nom":"Alisson Temin","nomEleve":"Misti","matiere":"Analyse","imageMat":"assets/images/r.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-03-14","note":10},
{"id":238,"nom":"Alisson Temin","nomEleve":"Alena","matiere":"Analyse","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-03-20","note":4},
{"id":225,"nom":"Gregory Galli","nomEleve":"See","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2021-01-17","note":18},
{"id":245,"nom":"Gabriel Mopolo","nomEleve":"Melonie","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-12-20","note":5},
{"id":280,"nom":"Gabriel Mopolo","nomEleve":"Laraine","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2021-02-14","note":10},
{"id":250,"nom":"Alisson Temin","nomEleve":"Hilliary","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-11-08","note":14},
{"id":284,"nom":"Alisson Temin","nomEleve":"Teirtza","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-06-19","note":5},
{"id":302,"nom":"Serge Miranda","nomEleve":"Mario","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-10-18","note":14},
{"id":263,"nom":"Serge Miranda","nomEleve":"Read","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-10-18","note":5},
{"id":268,"nom":"Serge Miranda","nomEleve":"Farlee","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-04-21","note":16},
{"id":219,"nom":"Alisson Temin","nomEleve":"Madeleine","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2021-01-16","note":16},
{"id":250,"nom":"Gabriel Mopolo","nomEleve":"Orelle","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-04-20","note":14},
{"id":244,"nom":"Gregory Galli","nomEleve":"Beitris","matiere":"Grails","imageMat":"assets/images/r.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-08-26","note":13},
{"id":201,"nom":"Serge Miranda","nomEleve":"Joli","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2021-02-28","note":2},
{"id":223,"nom":"Buffa Michel","nomEleve":"Constance","matiere":"Techno Web","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-07-04","note":15},
{"id":201,"nom":"Alisson Temin","nomEleve":"Casey","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-12-17","note":18},
{"id":243,"nom":"Serge Miranda","nomEleve":"Sheilah","matiere":"De Base de données à Big Data","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-07-26","note":6},
{"id":286,"nom":"Alisson Temin","nomEleve":"Peadar","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-07-25","note":16},
{"id":278,"nom":"Gabriel Mopolo","nomEleve":"Charissa","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-12-25","note":18},
{"id":273,"nom":"Gabriel Mopolo","nomEleve":"Jodie","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-03-20","note":1},
{"id":248,"nom":"Serge Miranda","nomEleve":"Gail","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-05-27","note":11},
{"id":214,"nom":"Gabriel Mopolo","nomEleve":"Pauletta","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-03-02","note":9},
{"id":280,"nom":"Serge Miranda","nomEleve":"Giselle","matiere":"De Base de données à Big Data","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-12-08","note":17},
{"id":269,"nom":"Buffa Michel","nomEleve":"Casie","matiere":"Techno Web","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-08-25","note":14},
{"id":216,"nom":"Buffa Michel","nomEleve":"Dewain","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-12-12","note":3},
{"id":207,"nom":"Gabriel Mopolo","nomEleve":"Ingeborg","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-01-02","note":11},
{"id":218,"nom":"Alisson Temin","nomEleve":"Marni","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-01-14","note":18},
{"id":301,"nom":"Gregory Galli","nomEleve":"Nollie","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-09-18","note":20},
{"id":281,"nom":"Buffa Michel","nomEleve":"Sherman","matiere":"Techno Web","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2021-01-25","note":15},
{"id":282,"nom":"Alisson Temin","nomEleve":"Sonnie","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-08-12","note":8},
{"id":248,"nom":"Buffa Michel","nomEleve":"Marietta","matiere":"Techno Web","imageMat":"assets/images/r.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-07-25","note":13},
{"id":209,"nom":"Buffa Michel","nomEleve":"Allan","matiere":"Techno Web","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-12-25","note":11},
{"id":278,"nom":"Buffa Michel","nomEleve":"Cathy","matiere":"Techno Web","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-06-10","note":7},
{"id":213,"nom":"Alisson Temin","nomEleve":"Aryn","matiere":"Analyse","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-05-03","note":17},
{"id":227,"nom":"Buffa Michel","nomEleve":"Susie","matiere":"Techno Web","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-08-28","note":12},
{"id":302,"nom":"Gregory Galli","nomEleve":"Belinda","matiere":"Grails","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-09-16","note":19},
{"id":279,"nom":"Alisson Temin","nomEleve":"Merell","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-05-27","note":15},
{"id":267,"nom":"Serge Miranda","nomEleve":"Therine","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-10-13","note":16},
{"id":221,"nom":"Serge Miranda","nomEleve":"Foster","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-04-11","note":6},
{"id":229,"nom":"Buffa Michel","nomEleve":"Lenci","matiere":"Techno Web","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-01-22","note":11},
{"id":248,"nom":"Buffa Michel","nomEleve":"Teodora","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-02-27","note":13},
{"id":223,"nom":"Gabriel Mopolo","nomEleve":"Theodore","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-11-20","note":2},
{"id":246,"nom":"Gabriel Mopolo","nomEleve":"Ric","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2021-01-13","note":12},
{"id":286,"nom":"Gabriel Mopolo","nomEleve":"Tybie","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-02-27","note":16},
{"id":302,"nom":"Gregory Galli","nomEleve":"Trueman","matiere":"Grails","imageMat":"assets/images/r.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-04-11","note":12},
{"id":271,"nom":"Serge Miranda","nomEleve":"Berget","matiere":"De Base de données à Big Data","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-12-20","note":14},
{"id":220,"nom":"Serge Miranda","nomEleve":"Rossie","matiere":"De Base de données à Big Data","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-04-17","note":2},
{"id":267,"nom":"Gregory Galli","nomEleve":"Dalston","matiere":"Grails","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-10-13","note":10},
{"id":294,"nom":"Alisson Temin","nomEleve":"Angela","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-08-28","note":12},
{"id":298,"nom":"Gabriel Mopolo","nomEleve":"Shelagh","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2021-02-12","note":20},
{"id":296,"nom":"Gregory Galli","nomEleve":"Adan","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-07-24","note":3},
{"id":218,"nom":"Gregory Galli","nomEleve":"Noreen","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-12-26","note":7},
{"id":240,"nom":"Gregory Galli","nomEleve":"Butch","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-06-17","note":17},
{"id":247,"nom":"Buffa Michel","nomEleve":"Lucine","matiere":"Techno Web","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-07-14","note":5},
{"id":286,"nom":"Gregory Galli","nomEleve":"Abigale","matiere":"Grails","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-01-12","note":14},
{"id":206,"nom":"Alisson Temin","nomEleve":"Ansley","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-03-22","note":10},
{"id":230,"nom":"Gregory Galli","nomEleve":"Angeline","matiere":"Grails","imageMat":"assets/images/r.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-01-29","note":8},
{"id":246,"nom":"Buffa Michel","nomEleve":"Vasilis","matiere":"Techno Web","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-05-25","note":18},
{"id":269,"nom":"Gabriel Mopolo","nomEleve":"Gabriellia","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-05-09","note":8},
{"id":230,"nom":"Gregory Galli","nomEleve":"Corrine","matiere":"Grails","imageMat":"assets/images/r.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-04-16","note":11},
{"id":229,"nom":"Buffa Michel","nomEleve":"Clotilda","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-11-21","note":20},
{"id":208,"nom":"Gabriel Mopolo","nomEleve":"Glyn","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-12-15","note":20},
{"id":279,"nom":"Buffa Michel","nomEleve":"Lusa","matiere":"Techno Web","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-04-12","note":18},
{"id":214,"nom":"Gabriel Mopolo","nomEleve":"Georgeanna","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-07-03","note":17},
{"id":271,"nom":"Gregory Galli","nomEleve":"Norri","matiere":"Grails","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2021-02-28","note":8},
{"id":256,"nom":"Alisson Temin","nomEleve":"Lynn","matiere":"Analyse","imageMat":"assets/images/r.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-07-18","note":3},
{"id":267,"nom":"Gregory Galli","nomEleve":"Dulcie","matiere":"Grails","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-02-25","note":1},
{"id":215,"nom":"Serge Miranda","nomEleve":"Mikey","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-10-11","note":18},
{"id":284,"nom":"Buffa Michel","nomEleve":"Maura","matiere":"Techno Web","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-04-16","note":17},
{"id":233,"nom":"Gabriel Mopolo","nomEleve":"Dorise","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-05-23","note":3},
{"id":210,"nom":"Alisson Temin","nomEleve":"Derick","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-06-25","note":8},
{"id":291,"nom":"Gregory Galli","nomEleve":"Tom","matiere":"Grails","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-09-21","note":12},
{"id":201,"nom":"Serge Miranda","nomEleve":"Baron","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-12-26","note":5},
{"id":236,"nom":"Gabriel Mopolo","nomEleve":"Laurel","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-09-12","note":14},
{"id":206,"nom":"Alisson Temin","nomEleve":"Mabelle","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-10-29","note":13},
{"id":234,"nom":"Gabriel Mopolo","nomEleve":"Flora","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-11-07","note":8},
{"id":280,"nom":"Buffa Michel","nomEleve":"Heddie","matiere":"Techno Web","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-04-23","note":2},
{"id":223,"nom":"Alisson Temin","nomEleve":"Thaxter","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-10-09","note":20},
{"id":236,"nom":"Serge Miranda","nomEleve":"Margot","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-10-30","note":18},
{"id":270,"nom":"Gabriel Mopolo","nomEleve":"Gauthier","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-07-30","note":19},
{"id":206,"nom":"Alisson Temin","nomEleve":"Elfie","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-03-14","note":12},
{"id":222,"nom":"Gabriel Mopolo","nomEleve":"Tootsie","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-04-19","note":3},
{"id":249,"nom":"Serge Miranda","nomEleve":"Sophie","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-11-27","note":10},
{"id":203,"nom":"Buffa Michel","nomEleve":"Tarrance","matiere":"Techno Web","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-04-27","note":7},
{"id":215,"nom":"Gregory Galli","nomEleve":"Trumann","matiere":"Grails","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-05-13","note":14},
{"id":283,"nom":"Gregory Galli","nomEleve":"Bartholomew","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-05-09","note":3},
{"id":268,"nom":"Alisson Temin","nomEleve":"Kit","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-05-16","note":6},
{"id":280,"nom":"Alisson Temin","nomEleve":"Daniela","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-01-19","note":1},
{"id":230,"nom":"Gregory Galli","nomEleve":"Tucker","matiere":"Grails","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-10-21","note":19},
{"id":218,"nom":"Buffa Michel","nomEleve":"Rebeka","matiere":"Techno Web","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-09-13","note":14},
{"id":218,"nom":"Gabriel Mopolo","nomEleve":"Cecily","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-03-18","note":8},
{"id":242,"nom":"Buffa Michel","nomEleve":"Devin","matiere":"Techno Web","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-06-13","note":9},
{"id":285,"nom":"Gregory Galli","nomEleve":"Nedda","matiere":"Grails","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-10-07","note":1},
{"id":221,"nom":"Alisson Temin","nomEleve":"Lanie","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-08-02","note":11},
{"id":268,"nom":"Serge Miranda","nomEleve":"Joycelin","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-03-22","note":8},
{"id":267,"nom":"Alisson Temin","nomEleve":"Beau","matiere":"Analyse","imageMat":"assets/images/r.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-04-14","note":17},
{"id":259,"nom":"Alisson Temin","nomEleve":"Benjamin","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-11-21","note":10},
{"id":243,"nom":"Gabriel Mopolo","nomEleve":"Trevor","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-08-04","note":2},
{"id":288,"nom":"Gregory Galli","nomEleve":"Kris","matiere":"Grails","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-04-15","note":15},
{"id":282,"nom":"Buffa Michel","nomEleve":"Tom","matiere":"Techno Web","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-02-17","note":20},
{"id":243,"nom":"Alisson Temin","nomEleve":"Klaus","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-12-09","note":2},
{"id":267,"nom":"Buffa Michel","nomEleve":"Araldo","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-09-05","note":5},
{"id":286,"nom":"Gregory Galli","nomEleve":"Inga","matiere":"Grails","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-05-09","note":8},
{"id":228,"nom":"Gregory Galli","nomEleve":"Andre","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-07-20","note":7},
{"id":205,"nom":"Buffa Michel","nomEleve":"Antonino","matiere":"Techno Web","imageMat":"assets/images/db.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-09-11","note":2},
{"id":266,"nom":"Serge Miranda","nomEleve":"Biddie","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-04-24","note":10},
{"id":231,"nom":"Alisson Temin","nomEleve":"Ann-marie","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-03-03","note":13},
{"id":244,"nom":"Gregory Galli","nomEleve":"Robbin","matiere":"Grails","imageMat":"assets/images/r.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-06-03","note":4},
{"id":289,"nom":"Alisson Temin","nomEleve":"Fletch","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2021-01-06","note":11},
{"id":282,"nom":"Gregory Galli","nomEleve":"Gordie","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-06-06","note":4},
{"id":255,"nom":"Serge Miranda","nomEleve":"Zita","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-12-22","note":6},
{"id":203,"nom":"Gabriel Mopolo","nomEleve":"Antonin","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-03-26","note":2},
{"id":241,"nom":"Serge Miranda","nomEleve":"Germain","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-06-25","note":14},
{"id":203,"nom":"Serge Miranda","nomEleve":"Cassondra","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-06-17","note":20},
{"id":249,"nom":"Alisson Temin","nomEleve":"Galen","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-09-21","note":5},
{"id":290,"nom":"Buffa Michel","nomEleve":"Wat","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-07-05","note":9},
{"id":289,"nom":"Buffa Michel","nomEleve":"Rodina","matiere":"Techno Web","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-10-18","note":5},
{"id":295,"nom":"Buffa Michel","nomEleve":"Viola","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-01-26","note":4},
{"id":295,"nom":"Alisson Temin","nomEleve":"Katti","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-02-06","note":3},
{"id":293,"nom":"Gregory Galli","nomEleve":"Wallis","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-11-22","note":4},
{"id":265,"nom":"Gabriel Mopolo","nomEleve":"Neile","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-02-03","note":8},
{"id":270,"nom":"Alisson Temin","nomEleve":"Vin","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-05-27","note":8},
{"id":272,"nom":"Gregory Galli","nomEleve":"Franklyn","matiere":"Grails","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-07-02","note":6},
{"id":220,"nom":"Gregory Galli","nomEleve":"Phylys","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-05-06","note":16},
{"id":269,"nom":"Buffa Michel","nomEleve":"Yolanda","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-06-19","note":13},
{"id":254,"nom":"Serge Miranda","nomEleve":"Carrie","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-11-21","note":16},
{"id":271,"nom":"Alisson Temin","nomEleve":"Manon","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-03-10","note":18},
{"id":295,"nom":"Alisson Temin","nomEleve":"Quincy","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-05-14","note":11},
{"id":250,"nom":"Gabriel Mopolo","nomEleve":"Barbara-anne","matiere":"oracle","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-11-06","note":12},
{"id":292,"nom":"Gregory Galli","nomEleve":"Ginni","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-05-19","note":14},
{"id":254,"nom":"Alisson Temin","nomEleve":"Clemens","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-01-21","note":13},
{"id":260,"nom":"Buffa Michel","nomEleve":"Dyanne","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-11-21","note":6},
{"id":269,"nom":"Alisson Temin","nomEleve":"Byran","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-06-19","note":1},
{"id":244,"nom":"Gregory Galli","nomEleve":"Tannie","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-03-22","note":4},
{"id":290,"nom":"Gregory Galli","nomEleve":"Angy","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-10-08","note":2},
{"id":272,"nom":"Gregory Galli","nomEleve":"Nonna","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2021-02-24","note":1},
{"id":203,"nom":"Serge Miranda","nomEleve":"Yalonda","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-04-11","note":14},
{"id":287,"nom":"Serge Miranda","nomEleve":"Matthiew","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-11-18","note":3},
{"id":289,"nom":"Buffa Michel","nomEleve":"Blythe","matiere":"Techno Web","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-11-24","note":6},
{"id":300,"nom":"Alisson Temin","nomEleve":"Fleming","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-08-15","note":11},
{"id":294,"nom":"Serge Miranda","nomEleve":"Giulietta","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-11-10","note":14},
{"id":263,"nom":"Serge Miranda","nomEleve":"Adoree","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-12-18","note":16},
{"id":263,"nom":"Gregory Galli","nomEleve":"Diane","matiere":"Grails","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-04-02","note":4},
{"id":237,"nom":"Serge Miranda","nomEleve":"Teressa","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-11-19","note":7},
{"id":247,"nom":"Serge Miranda","nomEleve":"Myrtle","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-05-05","note":19},
{"id":293,"nom":"Gregory Galli","nomEleve":"Benedicta","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-07-17","note":18},
{"id":254,"nom":"Gregory Galli","nomEleve":"Ryley","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-12-21","note":10},
{"id":286,"nom":"Buffa Michel","nomEleve":"Dalston","matiere":"Techno Web","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-04-15","note":16},
{"id":302,"nom":"Gabriel Mopolo","nomEleve":"Holly-anne","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-05-02","note":6},
{"id":290,"nom":"Serge Miranda","nomEleve":"Kennett","matiere":"De Base de données à Big Data","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-04-07","note":7},
{"id":287,"nom":"Gabriel Mopolo","nomEleve":"Elmore","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2021-02-14","note":1},
{"id":248,"nom":"Gabriel Mopolo","nomEleve":"Ronnie","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-06-21","note":17},
{"id":222,"nom":"Serge Miranda","nomEleve":"Donetta","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-05-14","note":6},
{"id":268,"nom":"Serge Miranda","nomEleve":"Etienne","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-07-24","note":13},
{"id":299,"nom":"Serge Miranda","nomEleve":"Aldis","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-10-19","note":4},
{"id":235,"nom":"Alisson Temin","nomEleve":"Queenie","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-03-08","note":6},
{"id":281,"nom":"Gabriel Mopolo","nomEleve":"Aguistin","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-12-01","note":6},
{"id":260,"nom":"Serge Miranda","nomEleve":"Penni","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-11-07","note":6},
{"id":300,"nom":"Alisson Temin","nomEleve":"Eustace","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-03-25","note":11},
{"id":292,"nom":"Gregory Galli","nomEleve":"Liliane","matiere":"Grails","imageMat":"assets/images/r.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-10-03","note":12},
{"id":232,"nom":"Gabriel Mopolo","nomEleve":"Jens","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-03-27","note":12},
{"id":299,"nom":"Serge Miranda","nomEleve":"Avery","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-05-21","note":11},
{"id":230,"nom":"Gregory Galli","nomEleve":"Kittie","matiere":"Grails","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2021-01-03","note":19},
{"id":297,"nom":"Serge Miranda","nomEleve":"Lorri","matiere":"De Base de données à Big Data","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-08-05","note":4},
{"id":285,"nom":"Serge Miranda","nomEleve":"Selle","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-03-22","note":16},
{"id":237,"nom":"Gabriel Mopolo","nomEleve":"Shane","matiere":"oracle","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-04-14","note":11},
{"id":248,"nom":"Serge Miranda","nomEleve":"Felizio","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-08-21","note":2},
{"id":253,"nom":"Serge Miranda","nomEleve":"Lilas","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-07-19","note":14},
{"id":265,"nom":"Alisson Temin","nomEleve":"Imogene","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-09-07","note":17},
{"id":249,"nom":"Gabriel Mopolo","nomEleve":"Benson","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2021-01-06","note":3},
{"id":274,"nom":"Gabriel Mopolo","nomEleve":"Kelvin","matiere":"oracle","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-11-12","note":20},
{"id":290,"nom":"Alisson Temin","nomEleve":"Nahum","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-03-16","note":5},
{"id":288,"nom":"Alisson Temin","nomEleve":"Kris","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-07-24","note":13},
{"id":257,"nom":"Gabriel Mopolo","nomEleve":"Cody","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-04-12","note":1},
{"id":297,"nom":"Buffa Michel","nomEleve":"Vinny","matiere":"Techno Web","imageMat":"assets/images/db.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-09-08","note":18},
{"id":240,"nom":"Gabriel Mopolo","nomEleve":"De witt","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-12-12","note":3},
{"id":231,"nom":"Buffa Michel","nomEleve":"Moises","matiere":"Techno Web","imageMat":"assets/images/r.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-11-09","note":18},
{"id":204,"nom":"Buffa Michel","nomEleve":"Costa","matiere":"Techno Web","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-11-07","note":1},
{"id":301,"nom":"Buffa Michel","nomEleve":"Isiahi","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-08-03","note":13},
{"id":219,"nom":"Serge Miranda","nomEleve":"Horst","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-09-30","note":8},
{"id":275,"nom":"Serge Miranda","nomEleve":"Sonnie","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-03-16","note":10},
{"id":215,"nom":"Gabriel Mopolo","nomEleve":"Hildegaard","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-04-11","note":5},
{"id":296,"nom":"Serge Miranda","nomEleve":"Gwenore","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-08-04","note":17},
{"id":301,"nom":"Serge Miranda","nomEleve":"Rosella","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-10-05","note":17},
{"id":285,"nom":"Alisson Temin","nomEleve":"Sandi","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-12-12","note":9},
{"id":223,"nom":"Gregory Galli","nomEleve":"Marget","matiere":"Grails","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-07-11","note":2},
{"id":275,"nom":"Buffa Michel","nomEleve":"Callean","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-10-05","note":7},
{"id":273,"nom":"Serge Miranda","nomEleve":"Pepillo","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-10-06","note":18},
{"id":295,"nom":"Alisson Temin","nomEleve":"Jory","matiere":"Analyse","imageMat":"assets/images/r.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-12-07","note":5},
{"id":289,"nom":"Gregory Galli","nomEleve":"Vinnie","matiere":"Grails","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2021-02-10","note":10},
{"id":298,"nom":"Serge Miranda","nomEleve":"Cathrine","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-05-26","note":18},
{"id":213,"nom":"Alisson Temin","nomEleve":"Trisha","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-08-11","note":2},
{"id":219,"nom":"Gregory Galli","nomEleve":"Claretta","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-06-14","note":14},
{"id":252,"nom":"Gabriel Mopolo","nomEleve":"Merrilee","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-12-25","note":20},
{"id":290,"nom":"Gregory Galli","nomEleve":"Carolan","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-05-23","note":2},
{"id":256,"nom":"Gabriel Mopolo","nomEleve":"Berty","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-08-01","note":10},
{"id":244,"nom":"Gregory Galli","nomEleve":"Cordy","matiere":"Grails","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-01-30","note":13},
{"id":298,"nom":"Gregory Galli","nomEleve":"Reggie","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-11-16","note":7},
{"id":218,"nom":"Serge Miranda","nomEleve":"Kasey","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-12-14","note":12},
{"id":242,"nom":"Serge Miranda","nomEleve":"Jillene","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-05-14","note":2},
{"id":248,"nom":"Serge Miranda","nomEleve":"Marline","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-10-27","note":3},
{"id":294,"nom":"Gabriel Mopolo","nomEleve":"Lillis","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-05-31","note":16},
{"id":295,"nom":"Alisson Temin","nomEleve":"Lauraine","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-01-13","note":18},
{"id":205,"nom":"Buffa Michel","nomEleve":"Tedd","matiere":"Techno Web","imageMat":"assets/images/r.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-07-31","note":15},
{"id":282,"nom":"Serge Miranda","nomEleve":"Rock","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-11-22","note":16},
{"id":204,"nom":"Serge Miranda","nomEleve":"Daisie","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-01-01","note":5},
{"id":219,"nom":"Alisson Temin","nomEleve":"Rachel","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-02-02","note":19},
{"id":299,"nom":"Gregory Galli","nomEleve":"Ellsworth","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-05-03","note":16},
{"id":214,"nom":"Gabriel Mopolo","nomEleve":"Launce","matiere":"oracle","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-08-30","note":6},
{"id":253,"nom":"Gregory Galli","nomEleve":"Arvin","matiere":"Grails","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-07-28","note":16},
{"id":265,"nom":"Alisson Temin","nomEleve":"Ennis","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2021-02-16","note":12},
{"id":225,"nom":"Serge Miranda","nomEleve":"Ingemar","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-03-14","note":19},
{"id":268,"nom":"Alisson Temin","nomEleve":"Kori","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-12-05","note":9},
{"id":217,"nom":"Alisson Temin","nomEleve":"Ax","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-01-16","note":18},
{"id":204,"nom":"Serge Miranda","nomEleve":"Redd","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-01-22","note":16},
{"id":206,"nom":"Alisson Temin","nomEleve":"Candie","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2021-01-09","note":18},
{"id":206,"nom":"Gabriel Mopolo","nomEleve":"Morgun","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-09-24","note":1},
{"id":243,"nom":"Buffa Michel","nomEleve":"Derry","matiere":"Techno Web","imageMat":"assets/images/r.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-04-13","note":5},
{"id":239,"nom":"Gabriel Mopolo","nomEleve":"Halette","matiere":"oracle","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-03-31","note":20},
{"id":226,"nom":"Serge Miranda","nomEleve":"Ninetta","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-04-04","note":9},
{"id":246,"nom":"Serge Miranda","nomEleve":"Flin","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-03-06","note":13},
{"id":205,"nom":"Serge Miranda","nomEleve":"Ronny","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-09-09","note":6},
{"id":213,"nom":"Serge Miranda","nomEleve":"Elinore","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-09-22","note":12},
{"id":302,"nom":"Alisson Temin","nomEleve":"Lindsey","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-05-16","note":7},
{"id":229,"nom":"Buffa Michel","nomEleve":"Sanson","matiere":"Techno Web","imageMat":"assets/images/db.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-04-17","note":18},
{"id":211,"nom":"Gregory Galli","nomEleve":"Arnuad","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-04-13","note":15},
{"id":289,"nom":"Serge Miranda","nomEleve":"Nanice","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-08-01","note":15},
{"id":237,"nom":"Gregory Galli","nomEleve":"Ariella","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-12-20","note":5},
{"id":228,"nom":"Gregory Galli","nomEleve":"Marilyn","matiere":"Grails","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-08-10","note":18},
{"id":289,"nom":"Gabriel Mopolo","nomEleve":"Myron","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-11-15","note":17},
{"id":213,"nom":"Alisson Temin","nomEleve":"Abdel","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-12-21","note":15},
{"id":203,"nom":"Gabriel Mopolo","nomEleve":"Rachele","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-06-01","note":4},
{"id":258,"nom":"Gregory Galli","nomEleve":"Simmonds","matiere":"Grails","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-07-05","note":1},
{"id":300,"nom":"Gabriel Mopolo","nomEleve":"Harbert","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-10-14","note":8},
{"id":215,"nom":"Serge Miranda","nomEleve":"Marylou","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-10-25","note":16},
{"id":276,"nom":"Serge Miranda","nomEleve":"Valentino","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2021-01-03","note":1},
{"id":272,"nom":"Serge Miranda","nomEleve":"Chiarra","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-09-24","note":5},
{"id":225,"nom":"Alisson Temin","nomEleve":"Anastasia","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-07-15","note":6},
{"id":232,"nom":"Alisson Temin","nomEleve":"Reinald","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2021-01-08","note":5},
{"id":225,"nom":"Serge Miranda","nomEleve":"Khalil","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-06-27","note":13},
{"id":292,"nom":"Gabriel Mopolo","nomEleve":"Jeannette","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-08-21","note":11},
{"id":221,"nom":"Gabriel Mopolo","nomEleve":"Addi","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-08-10","note":11},
{"id":296,"nom":"Alisson Temin","nomEleve":"Frederick","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-09-06","note":17},
{"id":245,"nom":"Serge Miranda","nomEleve":"Jacky","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-04-11","note":20},
{"id":201,"nom":"Gregory Galli","nomEleve":"Mischa","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-01-07","note":6},
{"id":267,"nom":"Alisson Temin","nomEleve":"Wally","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-07-18","note":17},
{"id":253,"nom":"Alisson Temin","nomEleve":"Brendon","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-07-31","note":3},
{"id":209,"nom":"Gregory Galli","nomEleve":"Mario","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2021-02-16","note":4},
{"id":232,"nom":"Gabriel Mopolo","nomEleve":"Crista","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-03-11","note":1},
{"id":297,"nom":"Serge Miranda","nomEleve":"Glennis","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2021-02-03","note":11},
{"id":237,"nom":"Buffa Michel","nomEleve":"Pincas","matiere":"Techno Web","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-12-12","note":9},
{"id":288,"nom":"Gregory Galli","nomEleve":"Fredelia","matiere":"Grails","imageMat":"assets/images/db.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-08-29","note":14},
{"id":246,"nom":"Gabriel Mopolo","nomEleve":"Chrotoem","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-11-10","note":18},
{"id":257,"nom":"Serge Miranda","nomEleve":"Demetrius","matiere":"De Base de données à Big Data","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-11-25","note":12},
{"id":257,"nom":"Alisson Temin","nomEleve":"Jacquenette","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-11-20","note":13},
{"id":302,"nom":"Serge Miranda","nomEleve":"Lazare","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-06-13","note":1},
{"id":219,"nom":"Serge Miranda","nomEleve":"Freddi","matiere":"De Base de données à Big Data","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-11-15","note":16},
{"id":241,"nom":"Gregory Galli","nomEleve":"Lenora","matiere":"Grails","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-10-21","note":3},
{"id":266,"nom":"Serge Miranda","nomEleve":"Torrance","matiere":"De Base de données à Big Data","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-05-10","note":7},
{"id":251,"nom":"Buffa Michel","nomEleve":"Gelya","matiere":"Techno Web","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2021-01-30","note":13},
{"id":241,"nom":"Gabriel Mopolo","nomEleve":"Che","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-07-25","note":9},
{"id":221,"nom":"Alisson Temin","nomEleve":"Rodrick","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-08-24","note":3},
{"id":203,"nom":"Gregory Galli","nomEleve":"Rozanna","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-07-11","note":5},
{"id":259,"nom":"Buffa Michel","nomEleve":"Cullen","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-07-26","note":2},
{"id":252,"nom":"Alisson Temin","nomEleve":"Maximo","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-03-08","note":7},
{"id":241,"nom":"Alisson Temin","nomEleve":"Magdalene","matiere":"Analyse","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2021-01-13","note":20},
{"id":209,"nom":"Alisson Temin","nomEleve":"Lilly","matiere":"Analyse","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/R.jpg","dateDeRendu":"2021-02-28","note":14},
{"id":277,"nom":"Gregory Galli","nomEleve":"Stacey","matiere":"Grails","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-10-06","note":4},
{"id":216,"nom":"Buffa Michel","nomEleve":"Antony","matiere":"Techno Web","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-06-01","note":17},
{"id":212,"nom":"Serge Miranda","nomEleve":"Antoinette","matiere":"De Base de données à Big Data","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-04-13","note":17},
{"id":230,"nom":"Gabriel Mopolo","nomEleve":"Ramsey","matiere":"oracle","imageMat":"assets/images/ang.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-06-07","note":19},
{"id":213,"nom":"Gabriel Mopolo","nomEleve":"Thor","matiere":"oracle","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-07-27","note":3},
{"id":233,"nom":"Buffa Michel","nomEleve":"Luella","matiere":"Techno Web","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-10-20","note":2},
{"id":253,"nom":"Alisson Temin","nomEleve":"Lonny","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/R.jpg","dateDeRendu":"2021-02-26","note":18},
{"id":277,"nom":"Gabriel Mopolo","nomEleve":"Margaretha","matiere":"oracle","imageMat":"assets/images/r.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2020-11-13","note":14},
{"id":226,"nom":"Buffa Michel","nomEleve":"John","matiere":"Techno Web","imageMat":"assets/images/r.png","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-10-22","note":20},
{"id":241,"nom":"Serge Miranda","nomEleve":"Evie","matiere":"De Base de données à Big Data","imageMat":"assets/images/db.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-07-14","note":5},
{"id":291,"nom":"Serge Miranda","nomEleve":"Rabi","matiere":"De Base de données à Big Data","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/BD.jpg","dateDeRendu":"2020-12-11","note":19},
{"id":291,"nom":"Gregory Galli","nomEleve":"Issi","matiere":"Grails","imageMat":"assets/images/r.png","imageProf":"assets/images/R.jpg","dateDeRendu":"2020-12-28","note":7},
{"id":283,"nom":"Alisson Temin","nomEleve":"Fae","matiere":"Analyse","imageMat":"assets/images/grails.jpeg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-11-25","note":16},
{"id":286,"nom":"Gregory Galli","nomEleve":"Nevil","matiere":"Grails","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/G.jpg","dateDeRendu":"2020-05-11","note":20},
{"id":217,"nom":"Buffa Michel","nomEleve":"Hurleigh","matiere":"Techno Web","imageMat":"assets/images/oracle.jpg","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-08-28","note":5},
{"id":276,"nom":"Alisson Temin","nomEleve":"Risa","matiere":"Analyse","imageMat":"assets/images/db.png","imageProf":"assets/images/mopolo.jpg","dateDeRendu":"2021-01-01","note":14},
{"id":250,"nom":"Gabriel Mopolo","nomEleve":"Case","matiere":"oracle","imageMat":"assets/images/db.png","imageProf":"assets/images/TC.jpg","dateDeRendu":"2020-05-17","note":9}]
export {bdInitialAssignment}
